import type { HueResource } from './hue-v2-client';
import type { HueResourceReference, ResourceManager } from './resource-manager';

interface StateDefinition { name: string; type: ioBroker.CommonType; role: string; value?: ioBroker.StateValue; resource: HueResource; unit?: string; min?: number; max?: number; write?: boolean; }

/** Creates rooms and zones with their Hue API v2 scenes nested below the owning group. */
export class GroupObjectManager {
    public constructor(private readonly adapter: ioBroker.Adapter) {}
    public async sync(resources: ResourceManager): Promise<void> { await this.adapter.delObjectAsync('scenes', { recursive: true }); await this.syncGroupedContainerType('room', 'rooms', 'Hue rooms', resources); await this.syncGroupedContainerType('zone', 'zones', 'Hue zones', resources); }
    public async updateResource(resources: ResourceManager, resource: HueResource): Promise<void> {
        if (resource.type === 'scene') { await this.updateSceneStatus(resource); return; }
        if (resource.type !== 'grouped_light') return;
        for (const [type, root] of [['room','rooms'],['zone','zones']] as const) for (const c of resources.getByType(type)) if (this.getServiceReferences(c).some(r => r.rid === resource.id)) await this.updateGroupedLightValues(`${root}.${c.id}`, resource);
    }
    private async syncGroupedContainerType(type:'room'|'zone', root:'rooms'|'zones', rootName:string, resources:ResourceManager):Promise<void>{ await this.adapter.delObjectAsync(root,{recursive:true}); await this.adapter.extendObjectAsync(root,{type:'folder',common:{name:rootName},native:{}}); for(const c of resources.getByType(type)){ const m=this.asRecord(c.metadata); const name=this.asString(m?.name)??c.id; const gl=this.getServiceReferences(c).filter(r=>r.rtype==='grouped_light').map(r=>resources.getById(r.rid)).find((r):r is HueResource=>r!==undefined); const base=`${root}.${c.id}`; await this.adapter.extendObjectAsync(base,{type:'channel',common:{name},native:{hueResourceId:c.id,hueResourceType:c.type,groupedLightResourceId:gl?.id}}); await this.createInfoState(`${base}.name`,'Name',name); if(gl){ await this.createState(`${base}.command`,{name:'Command',type:'string',role:'json',value:'',resource:gl,write:true}); await this.syncGroupedLightStates(base,gl);} await this.syncScenesForGroup(base,c.id,c.type,resources); } }
    private async syncScenesForGroup(base:string,gid:string,gtype:string,resources:ResourceManager):Promise<void>{ const scenes=resources.getByType('scene').filter(s=>{const g=this.asRecord(s.group);return this.asString(g?.rid)===gid&&this.asString(g?.rtype)===gtype;}); if(!scenes.length)return; await this.adapter.extendObjectAsync(`${base}.scenes`,{type:'channel',common:{name:'Scenes'},native:{}}); for(const s of scenes){const m=this.asRecord(s.metadata);const name=this.asString(m?.name)??s.id;const b=`${base}.scenes.${s.id}`;await this.adapter.extendObjectAsync(b,{type:'channel',common:{name},native:{hueResourceId:s.id,hueResourceType:s.type,groupResourceId:gid,groupResourceType:gtype}});await this.createInfoState(`${b}.name`,'Name',name);await this.createState(`${b}.recall`,{name:'Recall',type:'boolean',role:'button',value:false,resource:s,write:true});const status=this.getSceneStatus(s);if(status!==undefined)await this.createState(`${b}.status`,{name:'Status',type:'string',role:'text',value:status,resource:s});}}
    private async updateSceneStatus(scene:HueResource):Promise<void>{const status=this.getSceneStatus(scene);if(status===undefined)return;const group=this.asRecord(scene.group);const gid=this.asString(group?.rid);const gtype=this.asString(group?.rtype);if(!gid)return;const root=gtype==='room'?'rooms':gtype==='zone'?'zones':undefined;if(!root)return;await this.adapter.setStateAsync(`${root}.${gid}.scenes.${scene.id}.status`,status,true);}
    private getSceneStatus(scene:HueResource):string|undefined{const status=this.asRecord(scene.status);return this.asString(status?.active);}
    private async syncGroupedLightStates(base:string,r:HueResource):Promise<void>{ const on=this.asRecord(r.on);if(typeof on?.on==='boolean')await this.createState(`${base}.on`,{name:'On',type:'boolean',role:'switch',value:on.on,resource:r,write:true});const d=this.asRecord(r.dimming);if(typeof d?.brightness==='number')await this.createState(`${base}.dimming`,{name:'Dimming',type:'number',role:'level.dimmer',value:d.brightness,unit:'%',min:0,max:100,resource:r,write:true});if(Object.prototype.hasOwnProperty.call(r,'color_temperature')){const ct=this.asRecord(r.color_temperature);const s=this.asRecord(ct?.mirek_schema);await this.createState(`${base}.color_temperature`,{name:'Color temperature',type:'number',role:'level.color.temperature',value:typeof ct?.mirek==='number'?ct.mirek:undefined,unit:'mired',min:this.asNumber(s?.mirek_minimum),max:this.asNumber(s?.mirek_maximum),resource:r,write:true});}if(Object.prototype.hasOwnProperty.call(r,'color')){const c=this.asRecord(r.color);const xy=this.asRecord(c?.xy);await this.createState(`${base}.color`,{name:'Color',type:'string',role:'text',value:typeof xy?.x==='number'&&typeof xy?.y==='number'?JSON.stringify({x:xy.x,y:xy.y}):'',resource:r,write:true});}}
    private async updateGroupedLightValues(base:string,r:HueResource):Promise<void>{const on=this.asRecord(r.on);if(typeof on?.on==='boolean')await this.adapter.setStateAsync(`${base}.on`,on.on,true);const d=this.asRecord(r.dimming);if(typeof d?.brightness==='number')await this.adapter.setStateAsync(`${base}.dimming`,d.brightness,true);const ct=this.asRecord(r.color_temperature);if(typeof ct?.mirek==='number')await this.adapter.setStateAsync(`${base}.color_temperature`,ct.mirek,true);const c=this.asRecord(r.color);const xy=this.asRecord(c?.xy);if(typeof xy?.x==='number'&&typeof xy?.y==='number')await this.adapter.setStateAsync(`${base}.color`,JSON.stringify({x:xy.x,y:xy.y}),true);}
    private async createState(id:string,d:StateDefinition):Promise<void>{const common:ioBroker.StateCommon={name:d.name,type:d.type,role:d.role,read:true,write:d.write??false};if(d.unit!==undefined)common.unit=d.unit;if(d.min!==undefined)common.min=d.min;if(d.max!==undefined)common.max=d.max;await this.adapter.extendObjectAsync(id,{type:'state',common,native:{hueResourceId:d.resource.id,hueResourceType:d.resource.type,idV1:d.resource.id_v1}});if(d.value!==undefined)await this.adapter.setStateAsync(id,d.value,true);}
    private async createInfoState(id:string,name:string,value:string):Promise<void>{await this.adapter.extendObjectAsync(id,{type:'state',common:{name,type:'string',role:'text',read:true,write:false},native:{}});await this.adapter.setStateAsync(id,value,true);}
    private getServiceReferences(r:HueResource):HueResourceReference[]{if(!Array.isArray(r.services))return[];return r.services.filter((e):e is HueResourceReference=>{if(typeof e!=='object'||e===null)return false;const x=e as Record<string,unknown>;return typeof x.rid==='string'&&typeof x.rtype==='string';});}
    private asRecord(v:unknown):Record<string,unknown>|undefined{return typeof v==='object'&&v!==null&&!Array.isArray(v)?v as Record<string,unknown>:undefined;} private asString(v:unknown):string|undefined{return typeof v==='string'?v:undefined;} private asNumber(v:unknown):number|undefined{return typeof v==='number'?v:undefined;}
}
